/**
 * Rasterise the favicon from its SVG source, and emit it as a data URL module.
 *
 *   jlpm build:favicon
 *
 * WHY A RASTER AT ALL. PRD §4.2 puts **Safari 17** in scope, and Safari does
 * not render an SVG referenced by `rel="icon"`. An SVG-only favicon therefore
 * leaves one supported browser with no icon at all. A PNG is the only format
 * every browser in §4.2 draws, so the SVG is the source and the PNG is built
 * from it — never hand-drawn, never edited.
 *
 * WHY A DATA URL AND NOT AN ASSET IMPORT. This one was measured the hard way.
 * `@jupyterlab/builder` loads `.png` as `asset/resource`, which makes webpack
 * resolve a runtime public path. Inside a **federated** module that resolution
 * produced a bare directory URL: the browser refused
 * `…/@d4n/shell-chrome/static` as a script with MIME type `text/html`, and the
 * WHOLE extension failed to load — splash, terminal bridge, adaptive theme and
 * the menu-bar overflow with it, not just the favicon. The selector-integrity
 * job caught it as one broken selector,
 * `body[data-d4n-menubar-overflow] #jp-menu-panel`, which is exactly the canary
 * that selector was registered to be. Emitting TypeScript keeps webpack out of
 * it entirely.
 *
 * WHY 64px. The tab draws it at 16 CSS px, so 64 covers a 4× display and
 * downscales cleanly. The mark is a disc and a wedge; nothing in it needs
 * hinting at 16px, which is why it was chosen for the bar (D-021).
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = dirname(dirname(fileURLToPath(import.meta.url)));
const SOURCE = join(REPO, 'packages', 'icons', 'svg', 'brand', 'favicon.svg');
const PNG_TARGET = join(
  REPO,
  'packages',
  'shell-chrome',
  'style',
  'favicon.png'
);
const TS_TARGET = join(
  REPO,
  'packages',
  'shell-chrome',
  'src',
  'generated',
  'favicon.ts'
);
const SIZE = 64;

const { chromium } = await import(
  join(REPO, 'node_modules', '@playwright', 'test', 'index.mjs')
).catch(
  () => import('file:///workspace/node_modules/@playwright/test/index.mjs')
);

const svg = readFileSync(SOURCE, 'utf8');
const browser = await chromium.launch();
// deviceScaleFactor stays 1: the SVG already declares 64×64, so scaling here
// would produce a 128px file that claims to be 64.
const page = await browser.newPage({
  viewport: { width: SIZE, height: SIZE },
  deviceScaleFactor: 1
});
// `omitBackground` keeps the corners the plate's `rx` rounds off transparent,
// rather than filling them white against whatever the tab background is.
await page.setContent(
  `<body style="margin:0;width:${SIZE}px;height:${SIZE}px">${svg}</body>`
);
await page.waitForTimeout(200);
const png = await page.screenshot({ omitBackground: true });
await browser.close();

writeFileSync(PNG_TARGET, png);

/** Split base64 so the generated module stays readable in a diff. */
function chunk(text) {
  const out = [];
  for (let index = 0; index < text.length; index += 76) {
    out.push(text.slice(index, index + 76));
  }
  return out;
}

const parts = chunk(png.toString('base64'));
const lines = [
  '/* GENERATED by scripts/render-favicon.mjs — do not edit.',
  ' *',
  ' * The favicon as a data URL. It is deliberately NOT an asset import: see',
  ' * the header of the generator for the federated-module failure that cost.',
  ' *',
  ' * Source: packages/icons/svg/brand/favicon.svg',
  ' */',
  'export const FAVICON_DATA_URL =',
  "  'data:image/png;base64,' +",
  ...parts.map(
    (part, index) => `  '${part}'${index === parts.length - 1 ? ';' : ' +'}`
  ),
  ''
];

mkdirSync(dirname(TS_TARGET), { recursive: true });
writeFileSync(TS_TARGET, lines.join('\n'), 'utf8');

console.log(
  `render-favicon: ${SIZE}×${SIZE}, ${png.length} bytes -> ` +
    `${PNG_TARGET.slice(REPO.length + 1)} and ${TS_TARGET.slice(REPO.length + 1)}`
);
